
plural_noun = input("Enter a Plural Noun: ")
adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
name = input("Enter a name: ")
weapon = input("Enter a weapon: ")
location = input("Entr a location: ")
medicine  = input("Enter a medicine: ")
address = input("Enter an Address: ")
danger = input("Enter a dangerous situation: ")
magic = input("Enter a witch: ")
wish1 = input("Make a wish: ")
wish2 = input("Make another wish: ")
wish3 = input("Last wish: ")


print("Once upon a time,there lived a boy named" + name)
print("He was an adventurous boy who loved hiking and" + verb)
print("His favorite activity was a very" + plural_noun)
print("One day," + name)
print("decided to go on a journey to fine the legendary" + weapon)
print("He packed his" + weapon)
print("and find his way to the" + location)
print("Along the way, he encountered a mysterious wizard who gave him a" + medicine)
print("He used the" + medicine)
print("to fine his way through the forest and eventually reached the" + address)
print("When he arrived, he found the room to be empty and" + danger)
print("He quickly realized that this was no ordinary" + location)
print("Inside, he found an encounter" + magic)
print("who granted him three wishes")
print("He wished for" + wish1)
print("and a" + wish2)
print("And a" + wish3)

